import Head from 'next/head';
import Header from '@/components/Header';
import React from 'react';

import Image from 'next/image';

const Aboutme = () => {
  return (
    <div>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <p className='text-[rgb(251,247,245)] text-2xl font-semibold text-center
       decoration-[#00AFF0] underline pt-5 pb-10'>About Us</p>

      <div className='flex flex-col items-center justify-center'>
        <Image src="/pngaaa.com-807746.png" alt='' height={200} width={200} />
        <p className='text-[rgb(251,247,245)] text-lg font-semibold text-center
       py-5 px-12 md:px-24'>"At Grease Guys, we understand that your
        time is valuable. That’s why we bring our top-tier mobile
        oil change service directly to you. Whether you're at home,
        at work, or anywhere in between, our team of experienced
        technicians will take care of your vehicle’s oil change
        on the spot. No more waiting in line at the shop or
        adjusting your schedule—we make car maintenance as convenient
        as it should be. Trust Grease Guys to keep your engine running
        smoothly, so you can keep going without the hassle."
        </p>
      </div>
    </div>
  );
}

export default Aboutme;
