import Head from 'next/head';
import Header from '@/components/Header';
import React from 'react';

import Image from 'next/image';

const Aboutme = () => {
  return (
    <div>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <p className='text-[rgb(251,247,245)] text-2xl font-semibold text-center
       decoration-[#9A0000] underline pt-5 pb-10'>About Us</p>

      <div className='flex flex-col items-center justify-center'>
        <Image src="/pngaaa.com-4993052.png" alt='' height={150} width={150} />
        <p className='text-[rgb(251,247,245)] text-lg font-semibold text-center
       py-5 px-12 md:px-24'>"Welcome to Boombox Digital, your premier partner
        in digital marketing excellence! Based on beautiful Vancouver Island,
        our mission is to help small businesses grow by offering
        top-of-the-line online marketing services. We specialize in crafting
        tailored marketing strategies for restaurants, real estate agents,
        and owners of small all the way to large sized companies. At Boombox Digital,
        we combine local expertise with innovative techniques to amplify
        your online presence and drive measurable results. Let us help you
        turn up the volume on your business success!"
        </p>
      </div>
    </div>
  );
}

export default Aboutme;
