import Head from 'next/head';
import Header from '@/components/Header';
import React from 'react';

import Image from 'next/image';

const Portfolio = () => {
  return (
    <div>
      <Head>
        <title>Blacksand</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div id="empty-portfolio" className='justify-center text-4xl flex flex-row
       items-center py-24 mx-auto mt-20'>
         <Image className='p-5' src="/pngaaa.com-7101583.png" alt=''
          height={150} width={150} />
          <div className='flex-col'>
      <h1 className='text-[rgb(251,247,245)] text-lg sm:text-2xl md:text-4xl font-semibold
       text-center px-5'>Be the first to level up your business!</h1>
      <h1 className='text-[rgb(251,247,245)] text-lg sm:text-2xl md:text-4xl font-semibold
       text-center p-5'>Check out our state of the art services!</h1>
       </div>
       </div>
    </div>
  );
}

export default Portfolio;
